pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Compile Java') {
            steps {
                sh 'javac hello-java/HelloWorld.java'
            }
        }

        stage('Run Program') {
            steps {
                sh 'java -cp hello-java HelloWorld'
            }
        }

    }
}